name: Mirror repo to apt-99

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy-apt

    steps:
      # Repo origem
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # Repo destino
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: apt-evils-in/apt-99
          token: ${{ secrets.DEPLOY_TOKEN }}
          path: target
          persist-credentials: true

      # Sync origem â†’ destino (mirror real)
      - name: Sync source to target
        run: |
          rsync -av --delete \
            --exclude '.git' \
            --exclude '.github' \
            ./ target/ || [[ $? == 24 ]]

      - name: Commit and push
        run: |
          cd target
          git config user.name "auto-deploy"
          git config user.email "deploy@github"
          git add -A
          git diff --cached --quiet || git commit -m "Mirror from apt.evils.in"
          git push
